# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
use_frameworks!

workspace 'MantleNullValuesOmit.xcworkspace'

def shared_pods
   pod 'Mantle', '2.1.0'
end

target 'MantleNullValuesOmit' do
    project 'MantleNullValuesOmit.xcodeproj'
    shared_pods
    
end

target 'MantleNullValuesOmitTests' do
    project 'MantleNullValuesOmit.xcodeproj'
    shared_pods
end

target 'MantleNullValuesOmitTestsHostApp' do
    project 'MantleNullValuesOmit.xcodeproj'
    
end
